"""'Init'

Revision ID: 3e402126f411
Revises: b450606f3fc9
Create Date: 2022-07-05 11:27:14.470203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e402126f411'
down_revision = 'b450606f3fc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phones',
    sa.Column('phone_number', sa.String(length=14), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('phone_number')
    )
    op.drop_column('contacts', 'phone1')
    op.drop_column('contacts', 'phone2')
    op.drop_column('contacts', 'phone3')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('phone3', sa.VARCHAR(length=14), nullable=True))
    op.add_column('contacts', sa.Column('phone2', sa.VARCHAR(length=14), nullable=True))
    op.add_column('contacts', sa.Column('phone1', sa.VARCHAR(length=14), nullable=True))
    op.drop_table('phones')
    # ### end Alembic commands ###
