"""'Init'

Revision ID: 517425513561
Revises: b43dc32cda46
Create Date: 2022-07-04 17:34:07.729473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517425513561'
down_revision = 'b43dc32cda46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('address', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'address')
    # ### end Alembic commands ###
