"""'Init'

Revision ID: b43dc32cda46
Revises: 941ffffa0cb7
Create Date: 2022-07-04 17:19:38.501939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43dc32cda46'
down_revision = '941ffffa0cb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_column('contacts', 'father_name')
    op.drop_column('contacts', 'first_name')
    op.drop_column('contacts', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('last_name', sa.VARCHAR(length=30), nullable=False))
    op.add_column('contacts', sa.Column('first_name', sa.VARCHAR(length=20), nullable=True))
    op.add_column('contacts', sa.Column('father_name', sa.VARCHAR(length=20), nullable=True))
    op.drop_column('contacts', 'name')
    # ### end Alembic commands ###
